// The per-Mac integration bundle: one directory every agent client is wired to.
//
//   ~/.apple-cua/bundle/
//     bundle.json                          stamp: version, content hash, the checkout that generated it
//     .claude-plugin/marketplace.json      Claude Code local marketplace
//     .agents/plugins/marketplace.json     Codex local marketplace
//     plugins/apple-cua/
//       .claude-plugin/plugin.json         Claude Code plugin manifest
//       .codex-plugin/plugin.json          Codex plugin manifest
//       .mcp.json                          the signed helper, server.js and the saved settings as env
//       gemini-extension.json              Gemini CLI extension manifest (the same server)
//       skills/apple-cua/                  the skill, copied from the checkout
//
// Clients that copy plugins into a cache (Claude Code, Codex) decide whether to update by the version, so the version
// carries a hash of everything else in the bundle: the same content always has the same version, which makes setup
// idempotent, and any change (settings, skill text, a new checkout path) produces a new one.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import type { LaunchCommand } from "./clients.js";

export const PLUGIN_NAME = "apple-cua";
export const MARKETPLACE_NAME = "apple-cua-local";
export const MCP_SERVER_NAME = "apple-cua";
export const PLUGIN_DIRECTORY = `plugins/${PLUGIN_NAME}`;
export const SKILL_DIRECTORY = `${PLUGIN_DIRECTORY}/skills/apple-cua`;
const STAMP_FILE = "bundle.json";
const HOMEPAGE = "https://github.com/trac3r00/apple-cua";
const DESCRIPTION =
	"Operate macOS apps you approve, and an iPhone through iPhone Mirroring, through the signed apple-cua-mcp helper: observe, act, verify, and stop when unsure.";

export interface BundleFile {
	/** Relative to the bundle root, with forward slashes. */
	readonly path: string;
	readonly content: string;
}

export interface BundleInputs {
	readonly checkout: string;
	/** apple-cua's own version (packages/mcp/package.json); the content hash is appended to it. */
	readonly baseVersion: string;
	readonly launch: LaunchCommand;
	/** The saved settings as the server's environment; only keys with a value. */
	readonly env: Readonly<Record<string, string>>;
	/** The skill's files, paths relative to skills/apple-cua. */
	readonly skill: readonly BundleFile[];
}

export interface BundlePlan {
	/** `<baseVersion>+codex.<hash>`: Codex requires that cachebuster form, and Claude Code accepts it. */
	readonly version: string;
	readonly hash: string;
	readonly checkout: string;
	readonly files: readonly BundleFile[];
}

export interface BundleStamp {
	readonly version: string;
	readonly hash: string;
	readonly checkout: string;
}

function json(value: unknown): string {
	return `${JSON.stringify(value, null, 2)}\n`;
}

function manifests(inputs: BundleInputs, version: string): BundleFile[] {
	const author = { name: "apple-cua", url: HOMEPAGE };
	return [
		{
			path: ".claude-plugin/marketplace.json",
			content: json({
				name: MARKETPLACE_NAME,
				description: "apple-cua as installed on this Mac, generated by apple-cua setup",
				owner: { name: "apple-cua" },
				plugins: [
					{
						name: PLUGIN_NAME,
						source: `./${PLUGIN_DIRECTORY}`,
						description: DESCRIPTION,
						version,
						category: "productivity",
					},
				],
			}),
		},
		{
			path: ".agents/plugins/marketplace.json",
			content: json({
				name: MARKETPLACE_NAME,
				interface: { displayName: "apple-cua (this Mac)" },
				plugins: [
					{
						name: PLUGIN_NAME,
						source: { source: "local", path: `./${PLUGIN_DIRECTORY}` },
						policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
						category: "Productivity",
					},
				],
			}),
		},
		{
			path: `${PLUGIN_DIRECTORY}/.claude-plugin/plugin.json`,
			content: json({
				name: PLUGIN_NAME,
				version,
				description: DESCRIPTION,
				author,
				homepage: HOMEPAGE,
				repository: HOMEPAGE,
				license: "MIT",
				keywords: ["macos", "computer-use", "accessibility", "mcp", "iphone-mirroring"],
			}),
		},
		{
			// Gemini CLI links the plugin folder as an extension: the MCP server from here, the skill from skills/.
			path: `${PLUGIN_DIRECTORY}/gemini-extension.json`,
			content: json({
				name: PLUGIN_NAME,
				version,
				description: DESCRIPTION,
				mcpServers: { [MCP_SERVER_NAME]: mcpServer(inputs) },
			}),
		},
		{
			path: `${PLUGIN_DIRECTORY}/.codex-plugin/plugin.json`,
			content: json({
				name: PLUGIN_NAME,
				version,
				description: DESCRIPTION,
				author,
				homepage: HOMEPAGE,
				repository: HOMEPAGE,
				license: "MIT",
				keywords: ["macos", "computer-use", "accessibility", "mcp", "iphone-mirroring"],
				skills: "./skills/",
				mcpServers: "./.mcp.json",
				interface: {
					displayName: "apple-cua",
					shortDescription: "Drive the Mac apps you approve, in the background",
					longDescription: DESCRIPTION,
					developerName: "apple-cua",
					category: "Productivity",
					capabilities: ["Interactive", "Write"],
					websiteURL: HOMEPAGE,
					defaultPrompt: ["Open TextEdit and write a short note", "What apps can you drive on this Mac?"],
				},
			}),
		},
	];
}

/** The parts of the bundle that do not carry the version; their hash is the version's suffix. */
function contentFiles(inputs: BundleInputs): BundleFile[] {
	return [
		{
			path: `${PLUGIN_DIRECTORY}/.mcp.json`,
			content: json({ mcpServers: { [MCP_SERVER_NAME]: mcpServer(inputs) } }),
		},
		{
			// Codex reads a skill's agents/openai.yaml: the skill needs the plugin's MCP server.
			path: `${SKILL_DIRECTORY}/agents/openai.yaml`,
			content: [
				"interface:",
				'  display_name: "apple-cua"',
				'  short_description: "Operate approved macOS apps through the apple-cua MCP server"',
				"policy:",
				"  allow_implicit_invocation: true",
				"dependencies:",
				"  tools:",
				'    - type: "mcp"',
				`      value: "${MCP_SERVER_NAME}"`,
				"",
			].join("\n"),
		},
		...inputs.skill
			.filter((file) => file.path !== "agents/openai.yaml")
			.map((file) => ({ path: `${SKILL_DIRECTORY}/${file.path}`, content: file.content })),
	];
}

function byPath(left: BundleFile, right: BundleFile): number {
	return left.path < right.path ? -1 : left.path > right.path ? 1 : 0;
}

function mcpServer(inputs: BundleInputs): Record<string, unknown> {
	return {
		command: inputs.launch.command,
		args: [...inputs.launch.args],
		...(Object.keys(inputs.env).length === 0 ? {} : { env: { ...inputs.env } }),
	};
}

function hashFiles(files: readonly BundleFile[]): string {
	const digest = createHash("sha256");
	for (const file of [...files].sort(byPath)) {
		digest.update(file.path).update("\0").update(file.content).update("\0");
	}
	return digest.digest("hex").slice(0, 12);
}

/** Everything the bundle holds, and its version. Pure: the same inputs always give the same plan. */
export function planBundle(inputs: BundleInputs): BundlePlan {
	const content = contentFiles(inputs);
	// Hash the manifests too (with a fixed placeholder version), so a change to their template is a new version.
	const hash = hashFiles([...content, ...manifests(inputs, "0.0.0"), { path: "checkout", content: inputs.checkout }]);
	const version = `${inputs.baseVersion.split("+")[0]}+codex.${hash}`;
	const stamp: BundleStamp = { version, hash, checkout: inputs.checkout };
	return {
		version,
		hash,
		checkout: inputs.checkout,
		files: [...manifests(inputs, version), ...content, { path: STAMP_FILE, content: json(stamp) }].sort(byPath),
	};
}

/** The skill's files under `directory`, paths relative to it; .DS_Store and other dotfiles are skipped. */
export function readSkillFiles(directory: string): BundleFile[] {
	const files: BundleFile[] = [];
	const walk = (current: string) => {
		for (const entry of readdirSync(current).sort()) {
			if (entry.startsWith(".")) {
				continue;
			}
			const path = join(current, entry);
			if (statSync(path).isDirectory()) {
				walk(path);
			} else {
				files.push({ path: relative(directory, path), content: readFileSync(path, "utf8") });
			}
		}
	};
	walk(directory);
	return files;
}

export function readBundleStamp(bundleDir: string): BundleStamp | undefined {
	try {
		const parsed: unknown = JSON.parse(readFileSync(join(bundleDir, STAMP_FILE), "utf8"));
		if (typeof parsed !== "object" || parsed === null) {
			return undefined;
		}
		const { version, hash, checkout } = Object.fromEntries(Object.entries(parsed));
		return typeof version === "string" && typeof hash === "string" && typeof checkout === "string"
			? { version, hash, checkout }
			: undefined;
	} catch {
		return undefined;
	}
}

function listFiles(root: string): string[] {
	if (!existsSync(root)) {
		return [];
	}
	const files: string[] = [];
	const walk = (current: string) => {
		for (const entry of readdirSync(current)) {
			const path = join(current, entry);
			if (statSync(path).isDirectory()) {
				walk(path);
			} else {
				files.push(relative(root, path));
			}
		}
	};
	walk(root);
	return files.sort();
}

/** Whether the bundle on disk is exactly `plan`: the same files with the same content, and nothing else. */
export function bundleMatches(bundleDir: string, plan: BundlePlan): boolean {
	const onDisk = listFiles(bundleDir);
	if (onDisk.length !== plan.files.length) {
		return false;
	}
	return plan.files.every(
		(file, index) => onDisk[index] === file.path && readFileSync(join(bundleDir, file.path), "utf8") === file.content,
	);
}

export interface BundleWrite {
	readonly changed: boolean;
	readonly previous: BundleStamp | undefined;
}

/**
 * Makes `bundleDir` hold exactly `plan`. The new bundle is assembled beside the old one and swapped in with renames,
 * so a client never reads a half-written bundle and a stale file never survives. An identical bundle is left alone.
 */
export function writeBundle(bundleDir: string, plan: BundlePlan): BundleWrite {
	const previous = readBundleStamp(bundleDir);
	if (bundleMatches(bundleDir, plan)) {
		return { changed: false, previous };
	}
	const staging = `${bundleDir}.tmp-${process.pid}`;
	const retired = `${bundleDir}.old-${process.pid}`;
	rmSync(staging, { recursive: true, force: true });
	for (const file of plan.files) {
		const path = join(staging, file.path);
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, file.content, { mode: 0o644 });
	}
	mkdirSync(dirname(bundleDir), { recursive: true });
	if (existsSync(bundleDir)) {
		renameSync(bundleDir, retired);
	}
	renameSync(staging, bundleDir);
	rmSync(retired, { recursive: true, force: true });
	return { changed: true, previous };
}
