export const TOOL_NAMES = [
	"list_apps",
	"get_app_state",
	"click",
	"perform_secondary_action",
	"set_value",
	"set_fields",
	"run_steps",
	"select_text",
	"drag",
	"scroll",
	"type_text",
	"press_keys",
	"invoke_menu",
	"set_window_frame",
	"clipboard_read",
	"clipboard_write",
	"verify_state",
] as const;
